/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RaceIndexRouteImport } from './routes/race/index'
import { Route as RaceCodeRouteImport } from './routes/race/$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RaceIndexRoute = RaceIndexRouteImport.update({
  id: '/race/',
  path: '/race/',
  getParentRoute: () => rootRouteImport,
} as any)
const RaceCodeRoute = RaceCodeRouteImport.update({
  id: '/race/$code',
  path: '/race/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/race/$code': typeof RaceCodeRoute
  '/race/': typeof RaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/race/$code': typeof RaceCodeRoute
  '/race': typeof RaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/race/$code': typeof RaceCodeRoute
  '/race/': typeof RaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/race/$code' | '/race/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/race/$code' | '/race'
  id: '__root__' | '/' | '/race/$code' | '/race/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RaceCodeRoute: typeof RaceCodeRoute
  RaceIndexRoute: typeof RaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/race/': {
      id: '/race/'
      path: '/race'
      fullPath: '/race/'
      preLoaderRoute: typeof RaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/race/$code': {
      id: '/race/$code'
      path: '/race/$code'
      fullPath: '/race/$code'
      preLoaderRoute: typeof RaceCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RaceCodeRoute: RaceCodeRoute,
  RaceIndexRoute: RaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
